version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./wog_world:/wog_world  # Correct path to your project directory
    ports:
      - "8000:8000"
    networks:
      - mysql_db_network
    environment:
      - DJANGO_SETTINGS_MODULE=wog_world.settings
      - DATABASE_NAME=your_database_name
      - DATABASE_USER=root
      - DATABASE_PASSWORD=my_root_password
      - DATABASE_HOST=mysql_db  # Use the container name
      - DATABASE_PORT=3306
      

networks:
  mysql_db_network:
    external: true