version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_DATABASE: wog_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - wog_mysql_data_1:/var/lib/mysql
    networks:
      - mysql_db_network
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: my_root_password
    networks:
      - mysql_db_network
    ports:
      - "8080:80"

  web:
    build: .
    command: sh wog_world_init.sh
    volumes:
      - ./wog_world:/wog_world  # Correct path to your project directory
    ports:
      - "8000:8000"
    networks:
      - mysql_db_network
    depends_on:
      - mysql
    environment:
      - DJANGO_SETTINGS_MODULE=wog_world.settings
      - DATABASE_NAME=wog_db  # Adjust to match your database configuration
      - DATABASE_USER=my_user  # Match the MySQL user
      - DATABASE_PASSWORD=my_password  # Match the MySQL password
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306

networks:
  mysql_db_network:
    name: mysql_db_network  # Specify your desired network name here

volumes:
  wog_mysql_data_1:
