version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_DATABASE: wog_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - wog_mysql_data_1:/var/lib/mysql
    networks:
      - mysql_db_network
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: my_password
    networks:
      - mysql_db_network
    ports:
      - "8080:80"

networks:
  mysql_db_network:
    name: mysql_db_network  # Specify your desired network name here


volumes:
  wog_mysql_data_1: