# Generated by Django 4.2.15 on 2024-08-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_rename_games_game'),
    ]

    operations = [
    ]
