# Generated by Django 4.2.15 on 2024-08-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='css_class',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
